# docker compose YAML file used to spin up a WordPress site with a MySQL backend.

version: '3'

services:
  db:
    container_name: wp_mysql
    image: mysql:5.7
    volumes:
      - "$PWD/data:/var/lib/mysql"
    ports:
      - "3307:3306"
    networks:
      - my_net
    environment:
      MYSQL_ROOT_PASSWORD: 12345 
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp:
    container_name: wp_web
    image: wordpress
    ports:
      - "8080:80"
    networks:
      - my_net
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
networks:
  my_net:
